import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_excel('../comp_foc.xlsx', 'C2')
# df = df.set_index(['Champ (cm2)'])

plt.figure(figsize=(12, 7))
plt.plot(df['Champ (cm2)'], df['FOC Farmer'], 'x', label='Farmer')
plt.plot(df['Champ (cm2)'], df['CC13'], 'x', label='CC13')
plt.plot(df['Champ (cm2)'], df['Matrice 1600 SRS'], 'x', label='1600 SRS')
plt.plot(df['Champ (cm2)'], df['Matrice 1500'], 'x', label='1500')
plt.grid(ls='--')
plt.legend()
plt.xlabel('Taille de champ carré (cm)')
plt.ylabel('FOC')
plt.title('FOC pour différents détecteurs (Clinac 2 X6)')
plt.savefig('figures/comp_foc_C2.png', dpi=250)

df_films = pd.read_excel('../comp_foc.xlsx', 'Films X4 C3')
df_films = df_films.drop([0, 7])
plt.figure(figsize=(12, 7))
plt.plot(df_films['Cote champ carré (cm)'], df_films['FOC X4 film'], 'x')
plt.grid(ls='--')
plt.xlabel('Taille de champ carré (cm)')
plt.ylabel('FOC')
plt.title('FOC films EBT4 (Clinac 3 X4)')
plt.savefig('figures/foc_films_C3_X4.png', dpi=250)

# plt.figure(figsize=(12, 7))
# plt.plot(df['Champ (cm2)'], df['FOC Farmer'], 'x', label='Farmer')
# plt.plot(df['Champ (cm2)'], df['CC13'], 'x', label='CC13')
# plt.plot(df['Champ (cm2)'], df['Matrice 1600 SRS'], 'x', label='1600 SRS')
# plt.plot(df['Champ (cm2)'], df['Matrice 1500'], 'x', label='1500')
# plt.plot(df_films['Cote champ carré (cm)'], df_films['FOC X4 film'], 'x', label='Films EBT4')
# plt.grid(ls='--')
# plt.legend()
# plt.xlabel('Taille de champ carré (cm)')
# plt.ylabel('FOC')
# plt.title('FOC pour différents détecteurs')
# plt.show()